### ISSUE TITLE
No known class method for selector setupUrbanAirship

### ISSUE THREAD

**Issue by Fjandin** [globocom/react-native-ua#14]
I followed the guide from a to z, but when i try to compile i get `No known class method for selector 'setupUrbanAirship'`. Any idea of what i might have done wrong?

XCode Version 7.3.1 (7D1014)
React Native 0.31.0

**Comment by Fjandin** [comment]
So i figured out what was wrong.

The guide states that you should call
`[ReactNativeUAIOS setupUrbanAirship:launchOptions];`
While this method only exists without arguments.
`+ (void)setupUrbanAirship;`
So i changed it to
`[ReactNativeUAIOS setupUrbanAirship]`

**Comment by evandroeisinger** [comment]
Hey @Fjandin! We have not published in NPM the version that the documentation is referencing. Probably until next week we publish the new version soon.

Sorry about that!
