### ISSUE TITLE
Settings screen appear every time the app is opened?

### ISSUE THREAD

**Issue by olle-moren** [globocom/react-native-ua#25]
This happens due to

```
RCT_EXPORT_METHOD(enableNotification) {
    NSUserDefaults *defaults = [NSUserDefaults standardUserDefaults];

    [UAirship push].userPushNotificationsEnabled = YES;

    if ([defaults objectForKey:@"first_time_notification_enable"]) {

        [[UIApplication sharedApplication] openURL:[NSURL URLWithString:UIApplicationOpenSettingsURLString]];

    } else {

        [defaults setBool:YES forKey:@"first_time_notification_enable"];
        [defaults synchronize];

    }
}
```

in `react-native-ua/ios/ReactNativeUAIOS/ReactNativeUAIOS.m`

Can I turn this behaving off somehow?

**Comment by evandroeisinger** [comment]
hey @olle-moren-schibsted 

So, at this moment you should call `enableNotification` only once and control it calls according to your application behavior. Because every time you call it, it will ask the user to enable notifications.

We are open to pull requests 🎅  Any ideia is welcome!

**Comment by olle-moren** [comment]
Thanx for the info! It works fine now ⛵️
