### ISSUE TITLE
Adding a custom notification icon

### ISSUE THREAD

**Issue by justinwoo** [globocom/react-native-ua#28]
Hi, sorry, I've not been able to figure out how to add a custom notification icon.

I've added a PNG to use as my icon to both my src/main/ assets and res folders and tried to call ReactNativeUA.set_android_small_icon and set_android_large_icon with "myfile.png" but i haven't been able to replace my notification icon.

Could you advise on how I'm supposed to be doing this?

Thanks!

**Comment by justinwoo** [comment]
Ah, I see now that I was supposed to just use "myfile" without the extension and have it in my mipmap folders appropriately.

**Comment by evandroeisinger** [comment]
@justinwoo nice! This issue will help others with the same problem, sorry for the delay
