### ISSUE TITLE
Add Tag Response

### ISSUE THREAD

**Issue by cvongrim** [globocom/react-native-ua#38]
Any plans to return response so you can notify the user if they were successfully say added to a tagged group?

**Comment by cvongrim** [comment]
I started looking into a solution and found out that Urban Airship SDKs will automatically handle the retry internally if the tag operation fails to complete. So we really don't need to worry about it.

**Comment by evandroeisinger** [comment]
Yes! This why we initially didn't add response to `addTag` and others methods. The `react-native-ua` is just a bridge to the SDKs ;) Thanks for add the explanation into the issue!
