### ISSUE TITLE
Problem with iOS 

### ISSUE THREAD

**Issue by sumzer** [globocom/react-native-ua#43]
Hi,
I've followed all steps for iOS implementation and it doesn't work. 
Tried for RN 0.36, 0.39, 0.40
Push notifications simply doesn't work.
Android works from the box.

Did I miss something. Does someone have same problems?
Best regards
Sumi

**Comment by cparjaszewski** [comment]
It looks like few new versions of RN are introducing a lot of compatibility breaks. This library is a third-party for RN team, so probably not on the top of their priority list.
I had the same problem and needed to rollback to RN 0.34. But it's not a solution for the main problem.

**Comment by sumzer** [comment]
Hi,
finally I've managed to fix this.
This doesn't work with RN v0.40 but when doing downgrade I've not doing downgrade right, so I've created project with init for v.039.2 and it worked, 

react-native init --version="0.39.2" someInitProjectName

and when using push notification with my device used dev cert and AdHoc build.

Best regards
Sumi

**Comment by lucasts** [comment]
@sumzer Can we close this issue? 
as a side note, I think we need to improve docs to inform new versions of RN should be used with care. Their API is changing a lot and will probably break integrations.

**Comment by sumzer** [comment]
Hi, 
yeah, sure.
