### ISSUE TITLE
Update NPM package

### ISSUE THREAD

**Issue by djl-gg** [globocom/react-native-ua#49]
currently `get_channel_id` is not in my current package, however it looks to be updated in the git repository.  could someone update the package?

**Comment by djl-gg** [comment]
@azambuja @lucasts @rafaelmws @rfloriano @cyberelfo

**Comment by lucasts** [comment]
I will take a look @danieljoonlee. Thanks for the reminder.

**Comment by lucasts** [comment]
Done.

**Comment by djl-gg** [comment]
Thanks @lucasts !
