### ISSUE TITLE
Issues enabling/disabling push notifications on iOS

### ISSUE THREAD

**Issue by jortegano** [globocom/react-native-ua#55]
Hi, I'm having some issues with the process of enabling/disabling notifications on iOS. I'm only calling ReactNativeUA.enable_notification() the first time my app runs and I have these cases:

1. User accepts notifications request:
- After the user accepts, If the user goes to the OS settings screen and disables notifications for the app, the app stops receiving notifications as expected.
- If the user goes again to the OS settings screen and enables the notifications for the app, the app doesn't start to receive notifications again. What do I have to do? Do I need to call ReactNativeUA.enable_notification() again in order to syncronize data, device tokens, etc with urban airship service?

2. User rejects notifications request: After the user reject, if the user try to enable notifications via the OS settings screen the app doesn't start to receive any notifications

- What's the correct way to manage these cases?
- is there any way to get the user response to the call to ReactNativeUA.enable_notification()?
- is there any way to force a syncronization process(re-enable notifications, sync device token, etc) with urban airship service?

React-native version: 0.37.0
react-native-ua version: 1.0.0
iOS version: 8+

Thanks for your help, Jose.

**Comment by rlepinski** [comment]
@jortegano Are you starting the app again? Or leaving it in the background while you change those settings?

**Comment by jortegano** [comment]
@rlepinski, you're right. I was leaving the app in background. After fully closing the app and starting it again, everything works OK.
 
Sorry about that, I'm closing this issue. Thanks
